export const SET_PACKAGE = 'ADMIN/SET_PACKAGE';
export const DELETE_PACKAGE = 'ADMIN/DELETE_PACKAGE';
export const SET_PACKAGE_SUCCESS = 'ADMIN/SET_PACKAGE_SUCCESS';
export const SET_PACKAGE_FAILURE = 'ADMIN/SET_PACKAGE_FAILURE';
export const SET_PACKAGE_TITLE = 'ADMIN/SET_PACKAGE_TITLE';
export const SET_PACKAGE_DESCRIPTION = 'ADMIN/SET_PACKAGE_DESCRIPTION';
export const SET_PACKAGE_PRICE = 'ADMIN/SET_PACKAGE_PRICE';
export const SET_PACKAGE_IMAGE = 'ADMIN/SET_PACKAGE_IMAGE';
export const SET_TITLE_VALIDATION = 'ADMIN/SET_TITLE_VALIDATION';
export const SET_DESCRIPTION_VALIDATION = 'ADMIN/SET_DESCRIPTION_VALIDATION';
export const SET_PRICE_VALIDATION = 'ADMIN/SET_PRICE_VALIDATION';
export const SET_IMAGE_VALIDATION = 'ADMIN/SET_IMAGE_VALIDATION';

export const SET_EVENTS = 'ADMIN/SET_EVENTS';
export const SET_EVENTS_SUCCESS = 'ADMIN/SET_EVENTS_SUCCESS';
export const SET_EVENTS_FAILURE = 'ADMIN/SET_EVENTS_FAILURE';
export const SET_EVENT_ID = 'ADMIN/SET_EVENT_ID';
export const SET_EVENT_TITLE = 'ADMIN/SET_EVENT_TITLE';
export const SET_EVENT_DESCRIPTION = 'ADMIN/SET_EVENT_DESCRIPTION';

