export const SET_STUDENT = 'APP/SET_STUDENT';
export const CLEAR_STUDENT_DETAILS = 'APP/CLEAR_STUDENT_DETAILS';
export const SET_STUDENT_NAME = 'APP/SET_STUDENT_NAME';
export const SET_STUDENT_EMAIL = 'APP/SET_STUDENT_EMAIL';
export const SET_STUDENT_ADDRESS = 'APP/SET_STUDENT_ADDRESS';
export const SET_STUDENT_PHONE = 'APP/SET_STUDENT_PHONE';
export const SET_STUDENT_IMAGE = 'APP/SET_STUDENT_IMAGE';
export const SET_STUDENTS = 'APP/SET_STUDENTS';
export const SET_LOADING = 'APP/SET_LOADING';
export const SET_STUDENT_EDIT_POPUP = 'APP/SET_STUDENT_EDIT_POPUP';


export const VALID_STUDENT_NAME = 'APP/VALID_STUDENT_NAME';
export const VALID_STUDENT_EMAIL = 'APP/VALID_STUDENT_EMAIL';
export const VALID_STUDENT_ADDRESS = 'APP/VALID_STUDENT_ADDRESS';
export const VALID_STUDENT_PHONE = 'APP/VALID_STUDENT_PHONE';
export const VALID_STUDENT_IMAGE = 'APP/VALID_STUDENT_IMAGE';

export const SET_OPEN_SNACKBAR = 'APP/SET_OPEN_SNACKBAR';
export const SET_SNACKBAR_MESSAGE = 'APP/SET_SNACKBAR_MESSAGE';


export const SET_EVENTS = 'APP/SET_EVENTS';
export const UPDATE_EVENT = 'APP/UPDATE_EVENT';

export const SET_USER_INFO = 'APP/SET_USER_INFO';

