export const SET_CART = 'CART/SET_CART';
export const SET_CART_LOADING = 'CART/SET_CART_LOADING';
export const SET_CART_ERROR = 'CART/SET_CART_ERROR';
export const CLEAR_REDUCER = 'CART/CLEAR_REDUCER';
export const SET_CART_POPUP_SHOW = 'CART/SET_CART_POPUP_SHOW';