export const SET_PACKAGE = 'PACKAGE/SET_PACKAGE';
export const DELETE_PACKAGE = 'PACKAGE/DELETE_PACKAGE';
export const SET_PACKAGE_SUCCESS = 'PACKAGE/SET_PACKAGE_SUCCESS';
export const SET_PACKAGE_FAILURE = 'PACKAGE/SET_PACKAGE_FAILURE';
export const SET_PACKAGE_TITLE = 'PACKAGE/SET_PACKAGE_TITLE';
export const SET_PACKAGE_DESCRIPTION = 'PACKAGE/SET_PACKAGE_DESCRIPTION';
export const SET_PACKAGE_PRICE = 'PACKAGE/SET_PACKAGE_PRICE';
export const SET_PACKAGE_IMAGE = 'PACKAGE/SET_PACKAGE_IMAGE';
export const SET_TITLE_VALIDATION = 'PACKAGE/SET_TITLE_VALIDATION';
export const SET_DESCRIPTION_VALIDATION = 'PACKAGE/SET_DESCRIPTION_VALIDATION';
export const SET_PRICE_VALIDATION = 'PACKAGE/SET_PRICE_VALIDATION';
export const SET_IMAGE_VALIDATION = 'PACKAGE/SET_IMAGE_VALIDATION';
export const CLEAR_PACKAGE_DETAILS = 'PACKAGE/CLEAR_PACKAGE_DETAILS';

export const SET_EVENTS = 'EVENTS/SET_EVENTS';
export const SET_EVENTS_SUCCESS = 'EVENTS/SET_EVENTS_SUCCESS';
export const SET_EVENTS_FAILURE = 'EVENTS/SET_EVENTS_FAILURE';
export const SET_EVENT_ID = 'EVENTS/SET_EVENT_ID';
export const SET_EVENT_TITLE = 'EVENTS/SET_EVENT_TITLE';
export const SET_EVENT_DESCRIPTION = 'EVENTS/SET_EVENT_DESCRIPTION';

